#Configuracion del cliente
	#ejecucion de tarea ciclica
cliente.ciclico=no
	#numero de intentos antes de realizar el primer reporte  
cliente.intentos=3
	#intervalo de tiempo, en segundo, que se debe de esperar antes de realizar una llamada test
cliente.intervalo=30


#Configuracion de VPOS
	#indicador de si se debe ignorar los certificados del servicio
testvpos.ignore.certificate=true
	#URL o IP de Vpos 
#testvpos.url=https://localhost
testvpos.url=http://localhost
	#Puerto de Vpos
testvpos.puerto=8085

#Configuracion del servidor de correo
	#Tipo de seguridad usado por el servidor - NONE (ninguna), SSL, TLS
eserver.seguridad=NONE
	#IP del servidor de correo a utilizar para enviar los reportes
eserver.servidor=
	#Puerto del servidor de correos
eserver.puerto=
	#Usuario del servidor de correos
eserver.usuario=
	#Contrasena del servidor de correos
eserver.contrasena=

#Configuracion del correo
	#Correos destinatarios del aviso separados con un ";"
email.subjects=
	#Correos destinatarios con copia a, separados con un ;
email.subjects.carbon-copy=
	#Correos destinatarios con copia oculta a, separados con un ;
email.subjects.hidden-carbon-copy=
	#origen del correo
email.sender=
	#Titulo del correo
email.issuer=Alarma VPOS sin respuesta o innoperativo
	#Ruta donde se encuentra el cuerpo del correo
email.body=conf_test/cuerpo.txt
	#Ruta donde se enccuentra el archivo base para el adjunto del correo
email.file=conf_test/falla.txt